import { Fund, PortfolioData, HistoricalData, MarketIndicator, Alert } from '@/types/portfolio';

// Mock GPF Funds
export const mockFunds: Fund[] = [
    {
        id: 'gpf-eq-th',
        name: 'กองทุนหุ้นไทย',
        code: 'GPF-EQ-TH',
        type: 'equity',
        value: 1250000,
        units: 125000,
        navPerUnit: 10.00,
        allocation: 35,
        return1M: 2.5,
        return3M: 5.8,
        return6M: 12.3,
        return1Y: 18.5,
        returnYTD: 8.2,
        riskLevel: 4,
    },
    {
        id: 'gpf-eq-global',
        name: 'กองทุนหุ้นต่างประเทศ',
        code: 'GPF-EQ-GL',
        type: 'equity',
        value: 750000,
        units: 50000,
        navPerUnit: 15.00,
        allocation: 21,
        return1M: 1.8,
        return3M: 4.2,
        return6M: 9.5,
        return1Y: 15.2,
        returnYTD: 6.5,
        riskLevel: 5,
    },
    {
        id: 'gpf-fix-th',
        name: 'กองทุนตราสารหนี้ไทย',
        code: 'GPF-FIX-TH',
        type: 'fixed-income',
        value: 900000,
        units: 90000,
        navPerUnit: 10.00,
        allocation: 25,
        return1M: 0.3,
        return3M: 1.2,
        return6M: 2.5,
        return1Y: 4.8,
        returnYTD: 2.1,
        riskLevel: 2,
    },
    {
        id: 'gpf-fix-global',
        name: 'กองทุนตราสารหนี้ต่างประเทศ',
        code: 'GPF-FIX-GL',
        type: 'fixed-income',
        value: 400000,
        units: 40000,
        navPerUnit: 10.00,
        allocation: 11,
        return1M: 0.5,
        return3M: 1.5,
        return6M: 3.2,
        return1Y: 5.5,
        returnYTD: 2.8,
        riskLevel: 3,
    },
    {
        id: 'gpf-property',
        name: 'กองทุนอสังหาริมทรัพย์',
        code: 'GPF-PROP',
        type: 'property',
        value: 200000,
        units: 20000,
        navPerUnit: 10.00,
        allocation: 6,
        return1M: 0.8,
        return3M: 2.1,
        return6M: 4.5,
        return1Y: 8.2,
        returnYTD: 3.5,
        riskLevel: 3,
    },
    {
        id: 'gpf-alternative',
        name: 'กองทุนทางเลือก',
        code: 'GPF-ALT',
        type: 'alternative',
        value: 71429,
        units: 7143,
        navPerUnit: 10.00,
        allocation: 2,
        return1M: 1.2,
        return3M: 3.5,
        return6M: 7.8,
        return1Y: 12.5,
        returnYTD: 5.2,
        riskLevel: 4,
    },
];

// Calculate portfolio totals
const totalValue = mockFunds.reduce((sum, fund) => sum + fund.value, 0);
const weightedReturn = mockFunds.reduce((sum, fund) => sum + (fund.return1Y * fund.allocation / 100), 0);

export const mockPortfolio: PortfolioData = {
    totalValue: totalValue,
    todayChange: 28500,
    todayChangePercent: 0.82,
    totalReturn: totalValue * (weightedReturn / 100),
    totalReturnPercent: weightedReturn,
    funds: mockFunds,
    lastUpdated: new Date(),
};

// Historical performance data (last 12 months)
export const mockHistoricalData: HistoricalData[] = [
    { date: '2025-02', value: 2800000 },
    { date: '2025-03', value: 2950000 },
    { date: '2025-04', value: 2920000 },
    { date: '2025-05', value: 3050000 },
    { date: '2025-06', value: 3180000 },
    { date: '2025-07', value: 3250000 },
    { date: '2025-08', value: 3150000 },
    { date: '2025-09', value: 3280000 },
    { date: '2025-10', value: 3350000 },
    { date: '2025-11', value: 3420000 },
    { date: '2025-12', value: 3500000 },
    { date: '2026-01', value: 3571429 },
];

// Market indicators
export const mockMarketIndicators: MarketIndicator[] = [
    {
        id: 'set',
        name: 'ตลาดหลักทรัพย์ไทย',
        symbol: 'SET',
        value: 1456.82,
        change: 12.45,
        changePercent: 0.86,
        lastUpdated: new Date(),
    },
    {
        id: 'sp500',
        name: 'S&P 500',
        symbol: 'SPX',
        value: 5234.18,
        change: -8.32,
        changePercent: -0.16,
        lastUpdated: new Date(),
    },
    {
        id: 'dowjones',
        name: 'Dow Jones',
        symbol: 'DJI',
        value: 38456.23,
        change: 125.67,
        changePercent: 0.33,
        lastUpdated: new Date(),
    },
    {
        id: 'gold',
        name: 'ทองคำ',
        symbol: 'GOLD',
        value: 2042.50,
        change: 15.30,
        changePercent: 0.75,
        lastUpdated: new Date(),
    },
    {
        id: 'oil',
        name: 'น้ำมันดิบ',
        symbol: 'WTI',
        value: 78.45,
        change: -1.23,
        changePercent: -1.54,
        lastUpdated: new Date(),
    },
    {
        id: 'usdthb',
        name: 'USD/THB',
        symbol: 'USDTHB',
        value: 35.82,
        change: -0.15,
        changePercent: -0.42,
        lastUpdated: new Date(),
    },
];

// Alerts and notifications
export const mockAlerts: Alert[] = [
    {
        id: 'alert-1',
        type: 'warning',
        title: 'แนะนำปรับสมดุลพอร์ต',
        message: 'สัดส่วนหุ้นไทยสูงกว่าเป้าหมาย 5% ควรพิจารณาปรับสมดุล',
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
        read: false,
        actionRequired: true,
    },
    {
        id: 'alert-2',
        type: 'success',
        title: 'ผลตอบแทนดีเยี่ยม',
        message: 'พอร์ตของคุณทำผลตอบแทนสูงกว่าค่าเฉลี่ย 2.5% ในเดือนนี้',
        timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
        read: false,
        actionRequired: false,
    },
    {
        id: 'alert-3',
        type: 'info',
        title: 'อัพเดทตลาดโลก',
        message: 'ตลาดหุ้นสหรัฐฯ ปรับตัวขึ้น 0.5% หลังประกาศข้อมูลเศรษฐกิจ',
        timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
        read: true,
        actionRequired: false,
    },
    {
        id: 'alert-4',
        type: 'info',
        title: 'การลงทุนประจำเดือน',
        message: 'ระบบได้ทำการลงทุนประจำเดือนจำนวน 10,000 บาทเรียบร้อยแล้ว',
        timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
        read: true,
        actionRequired: false,
    },
];
